### ISSUE TITLE
Assign correct concept id to transdermal in vaccines liquibase setup once the concept is created.

### ISSUE THREAD

**Issue by jcairo** [sobolews/391_project#14]
There is no transdermal concept that I am aware of. I have temporarily assigned it to 123456. Once the concept is created we need to replace it with the concept id in the liquibase file and the route serializer.

**Comment by djphan** [comment]
Uh...... I think you created the wrong issue in the wrong project Jon.

**Comment by jcairo** [comment]
Right issue wrong repo. Thanks.
